package stericson.busybox.donate;


public class Constants {

	private static int		NONE = 0,
							UPDATE = 1,
							NEW = 2,
							BOTH = 3;

	public static int		updateType = UPDATE;
	
	public static String	EXTRA_BUSYBOX_VERSION = "version",
							EXTRA_INSTALL_PATH = "path",
							PREF_NAME = "BusyBox";
	
	public static String	newest = "BusyBox 1.20.1";
	public static String 	Key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk78EBO78KPQkOCo2SCPqImOv6ViRmY7Vy/d5xOi1+B1mJEWtHreHxrDw9sdyVaxbd3X/PnFIUQzj2Qk159RMP7p2lIiJ1yYVyifOciVV1f4r2z7llCKMJYCVVe0k+9P5SVEWZWoV+5QqJqm06pZ12ChsMNUN+3JujIUtiCARVn4wBmCT+eXfHcxmhyVfnE4a+3FlLGYrnCKE2B6AhcHXJXfPaW3K4P6JMDbWGoxO6yM/qPHqsfbsZK45Ooaqs1To2Oe6b7SaaAxAXPGipTCzQ7x8BRnMLkTMoLVDN0ABVlCgYpcWB9HysPALIXstSUWeGnF4WptkAfc34sQZm42DsQIDAQAB";
	
	public static String[] versions = { "BusyBox 1.20.1", "BusyBox 1.20.0", "BusyBox 1.19.4", "BusyBox 1.19.3", "BusyBox 1.19.2"};
	
	public static String[] locations = { "/system/bin", "/system/xbin", "Custom Path" };


	public static String[] appletsString = new String[] 
			{
				"[",
				"[[",
				"ash",
				"awk",
				"base64",
				"basename",
				"bunzip2",
				"bzip2",
				"blkid",
				"cal",
				"cat",
				"chat",
				"chattr",
				"chgrp",
				"chmod",
				"chown",
				"chroot",
				"chrt",
				"cksum",
				"clear",
				"comm",
				"cp",
				"crond",
				"crontab",
				"cut",
				"date",
				"dd",
				"depmod",
				"devmem",
				"df",
				"diff",
				"dirname",
				"dmesg",
				"dnsd",
				"dnsdomainname",
				"dos2unix",
				"du",
				"echo",
				"egrep",
				"env",
				"ether-wake",
				"expand",
				"expr",
				"fakeidentd",
				"fdflush",
				"fdformat",
				"fdisk",
				"fgrep",
				"find",
				"fold",
				"free",
				"freeramdisk",
				"fsck",
				"fsync",
				"ftpd",
				"ftpget",
				"ftpput",
				"getopt",
				"grep",
				"groups",
				"gunzip",
				"gzip",
				"hd",
				"head",
				"hexdump",
				"hostid",
				"hostname",
				"httpd",
				"hwclock",
				"id",
				"ifconfig",
				"ifenslave",
				"inetd",
				"inotifyd",
				"insmod",
				"install",
				"ionice",
				"iostat",
				"ip",
				"ipaddr",
				"ipcalc",
				"iplink",
				"iproute",
				"iprule",
				"iptunnel",
				"kill",
				"killall",
				"killall5",
				"less",
				"ln",
				"logname",
				"losetup",
				"ls",
				"lsattr",
				"lsmod",
				"lsusb",
				"lzop",
				"lzopcat",
				"md5sum",
				"mkdir",
				"mkdosfs",
				"microcom",
				"mke2fs",
				"mkfifo",
				"mkfs.ext2",
				"mkfs.vfat",
				"mknod",
				"mkswap",
				"modinfo",
				"modprobe",
				"more",
				"mount",
				"mt",
				"mv",
				"nameif",
				"nanddump",
				"nandwrite",
				"nc",
				"netstat",
				"nice",
				"nmeter",
				"nslookup",
				"ntpd",
				"od",
				"patch",
				"pgrep",
				"pidof",
				"ping",
				"ping6",
				"pkill",
				"pmap",
				"powertop",
				"printenv",
				"printf",
				"ps",
				"pscan",
				"pwd",
				"rdate",
				"rdev",
				"readahead",
				"readlink",
				"realpath",
				"renice",
				"reset",
				"rev",
				"rfkill",
				"rm",
				"rmdir",
				"rmmod",
				"route",
				"run-parts",
				"script",
				"scriptreplay",
				"sed",
				"seq",
				"setkeycodes",
				"setlogcons",
				"setsid",
				"sha1sum",
				"sha256sum",
				"sha512sum",
				"showkey",
				"sleep",
				"smemcap",
				"sort",
				"split",
				"stat",
				"strings",
				"stty",
				"sum",
				"swapoff",
				"swapon",
				"sync",
				"sysctl",
				"tac",
				"tail",
				"tar",
				"tee",
				"telnet",
				"telnetd",
				"test",
				"tftp",
				"tftpd",
				"time",
				"timeout",
				"top",
				"touch",
				"tr",
				"traceroute",
				"traceroute6",
				"tty",
				"ttysize",
				"tunctl",
				"umount",
				"uname",
				"uncompress",
				"unexpand",
				"uniq",
				"unix2dos",
				"unlzop",
				"unzip",
				"uptime",
				"usleep",
				"uudecode",
				"uuencode",
				"vconfig",
				"vi",
				"watch",
				"wc",
				"wget",
				"which",
				"who",
				"whoami",
				"whois",
				"xargs",
				"zcat"
			};
}
